# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto-Ride-Driver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto-Ride-Driver
  pod 'GeoFire', '~> 4.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'web3swift'

end

target 'Crypto-Ride-Passenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto-Ride-Passenger

end
